name: InfoSec Relations - Offensive Engineering - Marketplace

on: workflow_dispatch

jobs:
  GHA:
    runs-on: ubuntu-latest
    name: InfoSec Relations - Offensive Engineering - Fake GHA
    steps:
        - run: |
            id
            uname -a
        - uses: magnologan/fake-gha@v7
